// AUTH
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

// PRODUCTS
export const PRODUCTS_REQUEST = "PRODUCTS_REQUEST";
export const PRODUCTS_FAILURE = "PRODUCTS_FAILURE";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

// CART
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
